/**
 * Tiny typed wrapper around supabase.from(table).insert/update().
 *
 * Background: @supabase/ssr@0.5 + @supabase/supabase-js@2.106 + our
 * strict TS config combine to make `Relation['Insert']` resolve to
 * `any` on the .insert() call site even though the SupabaseClient is
 * fully typed against Database. The runtime is correct; only the
 * inferred payload type collapses. We isolate that collapse inside
 * this module — every call site stays typed against the generated
 * Insert/Update row shapes.
 */
import type { Database } from '@booking/types';

type Tables = Database['public']['Tables'];
export type TableName = keyof Tables;
export type Insert<T extends TableName> = Tables[T]['Insert'];
export type Update<T extends TableName> = Tables[T]['Update'];
export type Row<T extends TableName> = Tables[T]['Row'];

// We accept the broadly-typed client surface here precisely because
// the chain's terminal types are unstable in this version combo.
// Internally we trust the typed payload generated by the caller.
interface AnyClient {
  from(table: string): {
    insert(values: unknown): Promise<{ error: { message: string } | null }>;
    update(values: unknown): {
      eq(column: string, value: string): Promise<{ error: { message: string } | null }>;
    };
    delete(): {
      eq(column: string, value: string): Promise<{ error: { message: string } | null }>;
    };
  };
}

export async function insertRow<T extends TableName>(
  client: unknown,
  table: T,
  values: Insert<T>,
): Promise<void> {
  const c = client as AnyClient;
  const { error } = await c.from(table).insert(values);
  if (error) throw new Error(error.message);
}

export async function updateRow<T extends TableName>(
  client: unknown,
  table: T,
  id: string,
  values: Update<T>,
): Promise<void> {
  const c = client as AnyClient;
  const { error } = await c.from(table).update(values).eq('id', id);
  if (error) throw new Error(error.message);
}

export async function deleteRow<T extends TableName>(
  client: unknown,
  table: T,
  id: string,
): Promise<void> {
  const c = client as AnyClient;
  const { error } = await c.from(table).delete().eq('id', id);
  if (error) throw new Error(error.message);
}
